posAx = get(h.axMain,'Position');
units = get(h.axMain,'Units');
set(h.axMain,'Visible','off');
set(allchild(h.axMain),'visible','off'); 
ax1 = axes;
set(ax1,'Units',units);
set(ax1,'Position',[posAx(1) posAx(2) posAx(3) (posAx(4)-4)/3 ]);
ax2 = axes;
set(ax2,'Units',units);
set(ax2,'Position',[ posAx(1) posAx(2)+2+(posAx(4)-4)/3 posAx(3) (posAx(4)-4)/3]);
ax3 = axes;
set(ax3,'Units',units);
set(ax3,'Position',[ posAx(1) posAx(2)+4+2*(posAx(4)-4)/3 posAx(3) (posAx(4)-4)/3 ]);