function settings_gui_segmentation(f)

clf(f);
global p;
box_title = uicontrol('Style', 'text', ...
    'String', 'Segmentation', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [100, 460, 300, 30]);

%Nuclei ------------------------------------------------------------------
box_k1 = uicontrol('Style', 'text', ...
    'String', 'Nuclei k-means k:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 400, 250, 20]);
editbox_k1 = uicontrol('Style', 'edit', ...
    'String', p.DAPIseg.k, ...
    'Position', [250,400,50,20], ...
    'Callback', @saving_callback);

box_min_nucleus = uicontrol('Style', 'text', ...
    'String', 'Nuclei Min Amount Voxel:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 370, 250, 20]);
editbox_min_nucleus = uicontrol('Style', 'edit', ...
    'String', p.DAPIseg.minNucleusSize, ...
    'Position', [250,370,50,20], ...
    'Callback', @saving_callback);

%Landmark ----------------------------------------------------------------
box_k2 = uicontrol('Style', 'text', ...
    'String', 'Landmark k-means k:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 340, 250, 20]);
editbox_k2 = uicontrol('Style', 'edit', ...
    'String', p.GFPseg.k, ...
    'Position', [250,340,50,20], ...
    'Callback', @saving_callback);

box_min_voxels_gfp = uicontrol('Style', 'text', ...
    'String', 'Landmark Min Amount Voxel:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 310, 250, 20]);
editbox_min_voxels_gfp = uicontrol('Style', 'edit', ...
    'String', p.GFPseg.minNumberVoxels, ...
    'Position', [250,310,50,20], ...
    'Callback', @saving_callback);

box_filter_opening_gfp = uicontrol('Style', 'text', ...
    'String', 'Landmark Filtersize Opening:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 280, 250, 20]);
editbox_filter_opening_gfp = uicontrol('Style', 'edit', ...
    'String', p.GFPseg.size_opening, ...
    'Position', [250,280,50,20], ...
    'Callback', @saving_callback);

box_filter_closing_gfp = uicontrol('Style', 'text', ...
    'String', 'Landmark Filtersize Closing:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 250, 250, 20]);
editbox_filter_closing_gfp = uicontrol('Style', 'edit', ...
    'String', p.GFPseg.size_closing, ...
    'Position', [250,250,50,20], ...
    'Callback', @saving_callback);

%Cell Probe --------------------------------------------------------------
box_k3 = uicontrol('Style', 'text', ...
    'String', 'Cell Probe k-means k:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 220, 250, 20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Cells')));
editbox_k3 = uicontrol('Style', 'edit', ...
    'String', p.mCherryseg.k, ...
    'Position', [250,220,50,20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Cells')), ...
    'Callback', @saving_callback);

%Tissue Probe ------------------------------------------------------------
box_k4 = uicontrol('Style', 'text', ...
    'String', 'Tissue Probe k-means k:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 190, 250, 20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Tissue')));
editbox_k4 = uicontrol('Style', 'edit', ...
    'String', p.TISSUEseg.k, ...
    'Position', [250,190,50,20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Tissue')), ...
    'Callback', @saving_callback);

box_min_voxels_tissue = uicontrol('Style', 'text', ...
    'String', 'Tissue Probe Min Amount Voxel:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 160, 250, 20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Tissue')));
editbox_min_voxels_tissue = uicontrol('Style', 'edit', ...
    'String', p.TISSUEseg.minNumberVoxels, ...
    'Position', [250,160,50,20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Tissue')), ...
    'Callback', @saving_callback);

box_filter_opening_tissue = uicontrol('Style', 'text', ...
    'String', 'Tissue Probe Filtersize Opening:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 130, 250, 20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Tissue')));
editbox_filter_opening_tissue = uicontrol('Style', 'edit', ...
    'String', p.TISSUEseg.size_opening, ...
    'Position', [250,130,50,20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Tissue')), ...
    'Callback', @saving_callback);

box_filter_closing_tissue = uicontrol('Style', 'text', ...
    'String', 'Tissue Probe Filtersize Closing:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 100, 250, 20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Tissue')));
editbox_filter_closing_tissue = uicontrol('Style', 'edit', ...
    'String', p.TISSUEseg.size_closing, ...
    'Position', [250,100,50,20], ...
    'Enable', intern_function_bool_to_on_off(strcmp(p.mappingtype,'Tissue')), ...
    'Callback', @saving_callback);


button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 30, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        settings_gui_advanced(f);
    end

    function saving_callback(source, eventdata)
        p.DAPIseg.k = round(str2double(editbox_k1.String));
        editbox_k1.String = p.DAPIseg.k;
        p.GFPseg.k = round(str2double(editbox_k2.String));
        editbox_k2.String = p.GFPseg.k;
        p.mCherryseg.k = round(str2double(editbox_k3.String));
        editbox_k3.String = p.mCherryseg.k;
        p.TISSUEseg.k = round(str2double(editbox_k4.String));
        editbox_k4.String = p.TISSUEseg.k;
        p.DAPIseg.minNucleusSize = round(str2double(editbox_min_nucleus.String));
        editbox_min_nucleus.String = p.DAPIseg.minNucleusSize;
        p.GFPseg.minNumberVoxels = round(str2double(editbox_min_voxels_gfp.String));
        editbox_min_voxels_gfp.String = p.GFPseg.minNumberVoxels;
        p.GFPseg.size_opening = round(str2double(editbox_filter_opening_gfp.String));
        editbox_filter_opening_gfp.String = p.GFPseg.size_opening;
        p.GFPseg.size_closing = round(str2double(editbox_filter_closing_gfp.String));
        editbox_filter_closing_gfp.String = p.GFPseg.size_closing;
        p.TISSUEseg.minNumberVoxels = round(str2double(editbox_min_voxels_tissue.String));
        editbox_min_voxels_tissue.String = p.TISSUEseg.minNumberVoxels;
        p.TISSUEseg.size_opening = round(str2double(editbox_filter_opening_tissue.String));
        editbox_filter_opening_tissue.String = p.TISSUEseg.size_opening;
        p.TISSUEseg.size_closing = round(str2double(editbox_filter_closing_tissue.String));
        editbox_filter_closing_tissue.String = p.TISSUEseg.size_closing;
    end

    function s = intern_function_bool_to_on_off(x)
        if x
            s = 'on';
        else
           s = 'off';
        end
    end
end

