function settings_gui_ellipsoid_fitting(f)

clf(f);
global p;
box_title = uicontrol('Style', 'text', ...
    'String', 'Ellipsoid Fitting', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [150, 460, 200, 30]);


box_percentage = uicontrol('Style', 'text', ...
    'String', 'Random Sampling Percentage:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 410, 300, 25]);
editbox_percentage = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.percentage, ...
    'Position', [300,410,50,25], ...
    'Callback', @saving_callback);


box_mu0 = uicontrol('Style', 'text', ...
    'String', ['Parameter ' char(181) '0:'], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 360, 300, 25]);
editbox_mu0 = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.regularisationParams.mu0, ...
    'Position', [300,360,50,25], ...
    'Callback', @saving_callback);

box_mu1 = uicontrol('Style', 'text', ...
    'String', ['Parameter ' char(181) '1:'], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 310, 300, 25]);
editbox_mu1 = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.regularisationParams.mu1, ...
    'Position', [300,310,50,25], ...
    'Callback', @saving_callback);

box_mu2 = uicontrol('Style', 'text', ...
    'String', ['Parameter ' char(181) '2:'], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 260, 300, 25]);
editbox_mu2 = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.regularisationParams.mu2, ...
    'Position', [300,260,50,25], ...
    'Callback', @saving_callback);

box_gamma = uicontrol('Style', 'text', ...
    'String', 'Parameter Gamma:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 210, 300, 25]);
editbox_gamma = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.regularisationParams.gamma, ...
    'Position', [300,210,50,25], ...
    'Callback', @saving_callback);


button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 50, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        settings_gui_advanced(f);
    end

    function saving_callback(source, eventdata)
        p.ellipsoidFitting.percentage = str2double(editbox_percentage.String);
        p.ellipsoidFitting.regularisationParams.mu0 = str2double(editbox_mu0.String);
        p.ellipsoidFitting.regularisationParams.mu1 = str2double(editbox_mu1.String);
        p.ellipsoidFitting.regularisationParams.mu2 = str2double(editbox_mu2.String);
        p.ellipsoidFitting.regularisationParams.gamma = str2double(editbox_gamma.String);
    end
end

