function settings_gui_general(f)

clf(f);
global p;
box_ellipsoid_percentage = uicontrol('Style', 'text', ...
    'String', 'General', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [150, 460, 200, 30]);


box_debugging = uicontrol('Style', 'text', ...
    'String', 'Debug Level:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 400, 250, 30]);
button_debugging_0 = uicontrol('Style', 'radiobutton', ...
    'String', '0', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [250, 400, 50, 30], ...
    'Value', p.debug_level==0, ...
    'Callback', @saving_callback_debugging);
button_debugging_1 = uicontrol('Style', 'radiobutton', ...
    'String', '1', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [300, 400, 50, 30], ...
    'Value', p.debug_level==1, ...
    'Callback', @saving_callback_debugging);
button_debugging_2 = uicontrol('Style', 'radiobutton', ...
    'String', '2', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [350, 400, 50, 30], ...
    'Value', p.debug_level==2, ...
    'Callback', @saving_callback_debugging);

box_parallel = uicontrol('Style', 'text', ...
    'String', 'Parallel Pooling:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 350, 250, 30]);
checkbox_parallel = uicontrol('Style', 'checkbox', ...
    'Value', p.parallelpool, ...
    'Position', [250,355,30,30], ...
    'Callback', @saving_callback);

box_visualization = uicontrol('Style', 'text', ...
    'String', 'Visualization: ', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 300, 250, 30]);
checkbox_visualization = uicontrol('Style', 'checkbox', ...
    'Value', p.visualization, ...
    'Position', [250,305,30,30], ...
    'Callback', @saving_callback);

button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 50, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        settings_gui_advanced(f);
    end

    function saving_callback(source, eventdata)
        p.parallelpool = checkbox_parallel.Value;
        p.visualization = checkbox_visualization.Value;
    end

    function saving_callback_debugging(source, eventdata)
        if source==button_debugging_0
            button_debugging_0.Value = 1;
            button_debugging_1.Value = 0;
            button_debugging_2.Value = 0;
            p.debug_level = 0;
        elseif source==button_debugging_1
            button_debugging_0.Value = 0;
            button_debugging_1.Value = 1;
            button_debugging_2.Value = 0;
            p.debug_level = 1;
        else
            button_debugging_0.Value = 0;
            button_debugging_1.Value = 0;
            button_debugging_2.Value = 1;
            p.debug_level = 2;
        end
    end
end

