function settings_gui_ellipsoid_fitting(f)

clf(f);
global p;
box_title = uicontrol('Style', 'text', ...
    'String', 'Ellipsoid Fitting', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [100, 460, 300, 30]);


box_percentage = uicontrol('Style', 'text', ...
    'String', 'Random Sampling Percentage:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 400, 250, 20]);
editbox_percentage = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.percentage, ...
    'Position', [250,400,50,25], ...
    'Callback', @saving_callback);


box_mu0 = uicontrol('Style', 'text', ...
    'String', ['Parameter ' char(181) '0:'], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 370, 250, 20]);
editbox_mu0 = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.regularisationParams.mu0, ...
    'Position', [250,370,50,20], ...
    'Callback', @saving_callback);

box_mu1 = uicontrol('Style', 'text', ...
    'String', ['Parameter ' char(181) '1:'], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 340, 250, 20]);
editbox_mu1 = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.regularisationParams.mu1, ...
    'Position', [250,340,50,20], ...
    'Callback', @saving_callback);

box_mu2 = uicontrol('Style', 'text', ...
    'String', ['Parameter ' char(181) '2:'], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 310, 250, 20]);
editbox_mu2 = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.regularisationParams.mu2, ...
    'Position', [250,310,50,20], ...
    'Callback', @saving_callback);

box_gamma = uicontrol('Style', 'text', ...
    'String', 'Parameter Gamma:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 280, 250, 20]);
editbox_gamma = uicontrol('Style', 'edit', ...
    'String', p.ellipsoidFitting.regularisationParams.gamma, ...
    'Position', [250,280,50,20], ...
    'Callback', @saving_callback);

button_test_ellipsoid = uicontrol('Style', 'pushbutton', ...
    'String', 'Test ellipsoid', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [100, 100, 100, 50], ...
    'Callback', @button_test_ellipsoid_callback);
button_clear_test_data = uicontrol('Style', 'pushbutton', ...
    'String', 'Clear test data', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [300, 100, 100, 50], ...
    'Callback', @button_clear_test_data_callback);


button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 30, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        settings_gui_advanced(f);
    end

    function saving_callback(source, eventdata)
        p.ellipsoidFitting.percentage = str2double(editbox_percentage.String);
        p.ellipsoidFitting.regularisationParams.mu0 = str2double(editbox_mu0.String);
        p.ellipsoidFitting.regularisationParams.mu1 = str2double(editbox_mu1.String);
        p.ellipsoidFitting.regularisationParams.mu2 = str2double(editbox_mu2.String);
        p.ellipsoidFitting.regularisationParams.gamma = str2double(editbox_gamma.String);
    end

    function button_test_ellipsoid_callback(source, eventdata)
        test_ellipsoid(p);
    end

    function button_clear_test_data_callback(source, eventdata)
        clearvars -global nucleiTestCoordinates;
    end
end

