function settings_gui_heatmaps(f)

clf(f);
f.Position(4) = 700;
f.Position(2) = f.Position(2)-200;
global p;
box_title = uicontrol('Style', 'text', ...
    'String', 'Heatmaps', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [150, 660, 200, 30]);


box_dynamic_heatmapsize = uicontrol('Style', 'text', ...
    'String', 'Preserve XY-Ratio:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 610, 250, 30]);
checkbox_dynamic_heatmapsize = uicontrol('Style', 'checkbox', ...
    'Position', [250, 615, 30, 30], ...
    'Value', p.dynamicHeatmapsize, ...
    'Callback', @saving_callback_dynamic_heatmapsize);


box_gridsize = uicontrol('Style', 'text', ...
    'String', 'Accumulator Size:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 560, 250, 30], ...
    'Enable', intern_function_bool_to_on_off(~p.dynamicHeatmapsize));
editbox_gridsize_x = uicontrol('Style', 'edit', ...
    'String', p.gridSize(1), ...
    'Position', [250,560,50,30], ...
    'Enable', intern_function_bool_to_on_off(~p.dynamicHeatmapsize), ...
    'Callback', @saving_callback);
editbox_gridsize_y = uicontrol('Style', 'edit', ...
    'String', p.gridSize(2), ...
    'Position', [300,560,50,30], ...
    'Enable', intern_function_bool_to_on_off(~p.dynamicHeatmapsize), ...
    'Callback', @saving_callback);
editbox_gridsize_z = uicontrol('Style', 'edit', ...
    'String', p.gridSize(3), ...
    'Position', [350,560,50,30], ...
    'Enable', intern_function_bool_to_on_off(~p.dynamicHeatmapsize), ...
    'Callback', @saving_callback);

box_base_gridsize = uicontrol('Style', 'text', ...
    'String', 'Base Accumulator Size:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 510, 250, 30], ...
    'Enable', intern_function_bool_to_on_off(p.dynamicHeatmapsize));
editbox_base_gridsize = uicontrol('Style', 'edit', ...
    'String', p.gridSizeBaseValue, ...
    'Position', [250,510,50,30], ...
    'Enable', intern_function_bool_to_on_off(p.dynamicHeatmapsize), ...
    'Callback', @saving_callback);


box_shellheatmap_resolution = uicontrol('Style', 'text', ...
    'String', 'Shellheatmap Resolution:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 460, 250, 30], ...
    'Enable', intern_function_bool_to_on_off(~p.dynamicHeatmapsize));
editbox_shellheatmap_resolution_x = uicontrol('Style', 'edit', ...
    'String', p.option.shellHeatmapResolution(1), ...
    'Position', [250,460,50,30], ...
    'Enable', intern_function_bool_to_on_off(~p.dynamicHeatmapsize), ...
    'Callback', @saving_callback);
editbox_shellheatmap_resolution_y = uicontrol('Style', 'edit', ...
    'String', p.option.shellHeatmapResolution(2), ...
    'Position', [300,460,50,30], ...
    'Enable', intern_function_bool_to_on_off(~p.dynamicHeatmapsize), ...
    'Callback', @saving_callback);

box_base_shellheatmap_resolution = uicontrol('Style', 'text', ...
    'String', 'Base Shellheatmap Resolution:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 410, 300, 30], ...
    'Enable', intern_function_bool_to_on_off(p.dynamicHeatmapsize));
editbox_base_shellheatmap_resolution = uicontrol('Style', 'edit', ...
    'String', p.option.shellHeatmapResolutionBaseValue, ...
    'Position', [300,410,50,30], ...
    'Enable', intern_function_bool_to_on_off(p.dynamicHeatmapsize), ...
    'Callback', @saving_callback);


box_heatmap_saveas = uicontrol('Style', 'text', ...
    'String', 'Save Heatmaps as:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 360, 250, 30]);
checkbox_save_png = uicontrol('Style', 'checkbox', ...
    'String', '.png', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [250, 365, 50, 30], ...
    'Value', any(strcmp(p.option.heatmaps.saveas, 'png')), ...
    'Callback', @saving_callback_saveas);
checkbox_save_fig = uicontrol('Style', 'checkbox', ...
    'String', '.fig', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [350, 365, 50, 30], ...
    'Value', any(strcmp(p.option.heatmaps.saveas, 'fig')), ...
    'Callback', @saving_callback_saveas);

    
box_save_csv = uicontrol('Style', 'text', ...
    'String', 'Save as .csv:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 310, 300, 30]);
checkbox_save_csv = uicontrol('Style', 'checkbox', ...
    'Position', [250, 315, 30, 30], ...
    'Value', p.option.heatmaps.saveCSV, ...
    'Callback', @saving_callback);

box_save_acc = uicontrol('Style', 'text', ...
    'String', 'Save Accumulator File:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 260, 300, 30]);
checkbox_save_acc = uicontrol('Style', 'checkbox', ...
    'Position', [250, 265, 30, 30], ...
    'Value', p.option.heatmaps.saveAccumulator, ...
    'Callback', @saving_callback);

box_tolerance = uicontrol('Style', 'text', ...
    'String', 'Tolerance:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 210, 300, 30]);
editbox_tolerance = uicontrol('Style', 'edit', ...
    'String', p.tole, ...
    'Position', [250,210,50,30], ...
    'Callback', @saving_callback);

box_convolution = uicontrol('Style', 'text', ...
    'String', 'Convolution:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 160, 300, 30]);
checkbox_convolution = uicontrol('Style', 'checkbox', ...
    'Position', [250, 165, 30, 30], ...
    'Value', p.option.convolution, ...
    'Callback', @saving_callback_convolution);

box_celldiameter = uicontrol('Style', 'text', ...
    'String', ['Cell Diameter [' char(181) 'm]:'], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Enable', intern_function_bool_to_on_off(p.option.convolution), ...
    'Position', [10, 110, 250, 30]);
editbox_celldiameter = uicontrol('Style', 'edit', ...
    'String', p.cellDiameter_um, ...
    'Position', [250,110,50,30], ...
    'Enable', intern_function_bool_to_on_off(p.option.convolution), ...
    'Callback', @saving_callback);

button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 30, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        f.Position(4) = 500;
        f.Position(2) = f.Position(2) + 200;
        settings_gui_advanced(f);
    end

    function saving_callback_dynamic_heatmapsize(source, eventdata)
        p.dynamicHeatmapsize = checkbox_dynamic_heatmapsize.Value;
        if p.dynamicHeatmapsize
            box_gridsize.Enable = 'off';
            editbox_gridsize_x.Enable = 'off';
            editbox_gridsize_y.Enable = 'off';
            editbox_gridsize_z.Enable = 'off';
            box_base_gridsize.Enable = 'on';
            editbox_base_gridsize.Enable = 'on';
            
            box_shellheatmap_resolution.Enable = 'off';
            editbox_shellheatmap_resolution_x.Enable = 'off';
            editbox_shellheatmap_resolution_y.Enable = 'off';
            box_base_shellheatmap_resolution.Enable = 'on';
            editbox_base_shellheatmap_resolution.Enable = 'on';
        else
            box_gridsize.Enable = 'on';
            editbox_gridsize_x.Enable = 'on';
            editbox_gridsize_y.Enable = 'on';
            editbox_gridsize_z.Enable = 'on';
            box_base_gridsize.Enable = 'off';
            editbox_base_gridsize.Enable = 'off';
            
            box_shellheatmap_resolution.Enable = 'on';
            editbox_shellheatmap_resolution_x.Enable = 'on';
            editbox_shellheatmap_resolution_y.Enable = 'on';
            box_base_shellheatmap_resolution.Enable = 'off';
            editbox_base_shellheatmap_resolution.Enable = 'off';
        end
    end

    function saving_callback(source, eventdata)
        p.gridSize = [round(str2double(editbox_gridsize_x.String)); round(str2double(editbox_gridsize_y.String)); round(str2double(editbox_gridsize_z.String))];
        editbox_gridsize_x.String = p.gridSize(1);
        editbox_gridsize_y.String = p.gridSize(2);
        editbox_gridsize_z.String = p.gridSize(3);
        p.gridSizeBaseValue = round(str2double(editbox_base_gridsize.String));
        editbox_base_gridsize.String = p.gridSizeBaseValue;
        
        p.option.shellHeatmapResolution = [round(str2double(editbox_shellheatmap_resolution_x.String)), round(str2double(editbox_shellheatmap_resolution_y.String))];
        editbox_shellheatmap_resolution_x.String = p.option.shellHeatmapResolution(1);
        editbox_shellheatmap_resolution_y.String = p.option.shellHeatmapResolution(2);
        p.option.shellHeatmapResolutionBaseValue = round(str2double(editbox_base_shellheatmap_resolution.String));
        editbox_base_shellheatmap_resolution.String = p.option.shellHeatmapResolutionBaseValue;
        
        p.option.heatmaps.saveCSV = checkbox_save_csv.Value;
        p.option.heatmaps.saveAccumulator = checkbox_save_acc.Value;
        p.tole = str2double(editbox_tolerance.String);
        
        p.cellDiameter_um = str2double(editbox_celldiameter.String);
        p.cellDiameter = p.cellDiameter_um/(p.resolution(1));
    end

    function saving_callback_saveas(source, eventdata)
        if checkbox_save_png.Value
            if checkbox_save_fig.Value
                p.option.heatmaps.saveas = {'png','fig'};
            else
                p.option.heatmaps.saveas = {'png'};
            end
        elseif checkbox_save_fig.Value
            p.option.heatmaps.saveas = {'fig'};
        else
            p.option.heatmaps.saveas = {};
        end
    end

    function saving_callback_convolution(source, eventdata)
        p.option.convolution = checkbox_convolution.Value;
        box_celldiameter.Enable = intern_function_bool_to_on_off(p.option.convolution);
        editbox_celldiameter.Enable = intern_function_bool_to_on_off(p.option.convolution);
    end

    function s = intern_function_bool_to_on_off(x)
        if x
            s = 'on';
        else
           s = 'off';
        end
    end
end

