function settings_gui_preprocessing(f)

clf(f);
global p;
box_title = uicontrol('Style', 'text', ...
    'String', 'Preprocessing', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [100, 460, 300, 30]);


box_scale = uicontrol('Style', 'text', ...
    'String', 'Scaling Factor:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 400, 250, 20]);
editbox_scale = uicontrol('Style', 'edit', ...
    'String', p.scale, ...
    'Position', [250,400,50,20], ...
    'Callback', @saving_callback);

box_disk_dapi = uicontrol('Style', 'text', ...
    'String', 'Nuclei Filter Size:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 370, 250, 20]);
editbox_disk_dapi = uicontrol('Style', 'edit', ...
    'String', p.rmbg.dapiDiskSize, ...
    'Position', [250,370,50,20], ...
    'Callback', @saving_callback);
box_disk_gfp = uicontrol('Style', 'text', ...
    'String', 'Landmark Filter Size:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 340, 250, 20]);
editbox_disk_gfp = uicontrol('Style', 'edit', ...
    'String', p.rmbg.GFPDiskSize, ...
    'Position', [250,340,50,20], ...
    'Callback', @saving_callback);
box_disk_mcherry = uicontrol('Style', 'text', ...
    'String', 'Probe Filter Size:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 310, 250, 20]);
editbox_disk_mcherry = uicontrol('Style', 'edit', ...
    'String', p.rmbg.mCherryDiskSize, ...
    'Position', [250,310,50,20], ...
    'Callback', @saving_callback);


button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 30, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        settings_gui_advanced(f);
    end

    function saving_callback(source, eventdata)
        p.scale = str2double(editbox_scale.String);
        p.rmbg.dapiDiskSize = round(str2double(editbox_disk_dapi.String));
        editbox_disk_dapi.String = p.rmbg.dapiDiskSize;
        p.rmbg.GFPDiskSize = round(str2double(editbox_disk_gfp.String));
        editbox_disk_gfp.String = p.rmbg.GFPDiskSize;
        p.rmbg.mCherryDiskSize = round(str2double(editbox_disk_mcherry.String));
        editbox_disk_mcherry.String = p.rmbg.mCherryDiskSize;
    end
end

