function settings_gui_registration(f)

clf(f);
global p;
box_ellipsoid_percentage = uicontrol('Style', 'text', ...
    'String', 'Registration', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [150, 460, 200, 30]);


box_landmark_characteristic = uicontrol('Style', 'text', ...
    'String', 'Landmark Characteristic: ', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 410, 200, 25]);
editbox_landmark_characteristic = uicontrol('Style', 'edit', ...
    'String', p.reg.landmarkCharacteristic, ...
    'Position', [200,410,50,25], ...
    'Callback', @saving_callback);


box_characteristic_weight = uicontrol('Style', 'text', ...
    'String', 'Characteristic Weight: ', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 360, 200, 25]);
editbox_characteristic_weight = uicontrol('Style', 'edit', ...
    'String', p.reg.characteristicWeight, ...
    'Position', [200,360,50,25], ...
    'Callback', @saving_callback);


button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 50, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        settings_gui_advanced(f);
    end

    function saving_callback(source, eventdata)
        p.reg.landmarkCharacteristic = editbox_landmark_characteristic.String;
    end
end

