function settings_gui_preprocessing(f)

clf(f);
global p;
box_ellipsoid_percentage = uicontrol('Style', 'text', ...
    'String', 'Preprocessing', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [150, 460, 200, 30]);


box_scale = uicontrol('Style', 'text', ...
    'String', 'Scaling:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 400, 250, 30]);
editbox_scale = uicontrol('Style', 'edit', ...
    'String', p.scale, ...
    'Position', [250,400,50,30], ...
    'Callback', @saving_callback);

box_k1 = uicontrol('Style', 'text', ...
    'String', 'Nuclei k-means k:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 350, 250, 30]);
editbox_k1 = uicontrol('Style', 'edit', ...
    'String', p.DAPIseg.k, ...
    'Position', [250,350,50,30], ...
    'Callback', @saving_callback);

box_k2 = uicontrol('Style', 'text', ...
    'String', 'Landmark k-means k:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 300, 250, 30]);
editbox_k2 = uicontrol('Style', 'edit', ...
    'String', p.GFPseg.k, ...
    'Position', [250,300,50,30], ...
    'Callback', @saving_callback);

box_k3 = uicontrol('Style', 'text', ...
    'String', 'COI k-means k:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'Position', [10, 250, 250, 30]);
editbox_k3 = uicontrol('Style', 'edit', ...
    'String', p.mCherryseg.k, ...
    'Position', [250,250,50,30], ...
    'Callback', @saving_callback);

button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 50, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        settings_gui_advanced(f);
    end

    function saving_callback(source, eventdata)
        p.scale = str2double(editbox_scale.String);
        p.DAPIseg.k = str2double(editbox_k1.String);
        p.GFPseg.k = str2double(editbox_k2.String);
        p.mCherryseg.k = str2double(editbox_k3.String);
    end
end

