function settings_gui_registration(f)

clf(f);
global p;
box_title = uicontrol('Style', 'text', ...
    'String', 'Registration', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontSize', 20, ...
    'Position', [100, 460, 300, 30]);



box_characteristic_weight = uicontrol('Style', 'text', ...
    'String', 'Reference Position on Landmark:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10,400, 270, 20]);
editbox_characteristic_weight = uicontrol('Style', 'edit', ...
    'String', p.reg.characteristicWeight, ...
    'Position', [270,400,50,20], ...
    'Callback', @saving_callback);

box_reference_angle = uicontrol('Style', 'text', ...
    'String', 'Target Point [°]:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 370, 270, 20]);
editbox_reference_angle = uicontrol('Style', 'edit', ...
    'String', p.reg.angle, ...
    'Position', [270,370,50,20], ...
    'Callback', @saving_callback);


box_flipped = uicontrol('Style', 'text', ...
    'String', 'Flip Data:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10,340, 270, 20]);
checkbox_flipped = uicontrol('Style', 'checkbox', ...
    'Position', [270, 340, 75, 20], ...
    'Value', p.reg.flipped, ...
    'Callback', @saving_callback);

box_samples = uicontrol('Style', 'text', ...
    'String', 'Sphere Resolution:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 310, 270, 20]);
editbox_samples = uicontrol('Style', 'edit', ...
    'String', p.samples_sphere, ...
    'Position', [270,310,50,20], ...
    'Callback', @saving_callback);


box_samples_cube = uicontrol('Style', 'text', ...
    'String', 'Resolution Reference Cube:', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'Position', [10, 280, 270, 20]);
editbox_samples_cube_x = uicontrol('Style', 'edit', ...
    'String', p.samples_cube(1), ...
    'Position', [270,280,50,20], ...
    'Callback', @saving_callback);
editbox_samples_cube_y = uicontrol('Style', 'edit', ...
    'String', p.samples_cube(2), ...
    'Position', [320,280,50,20], ...
    'Callback', @saving_callback);
editbox_samples_cube_z = uicontrol('Style', 'edit', ...
    'String', p.samples_cube(3), ...
    'Position', [370,280,50,20], ...
    'Callback', @saving_callback);

button_back = uicontrol('Style', 'pushbutton', ...
    'FontName', 'Arial', ...
    'FontSize', 15, ...
    'String', 'Back', ...
    'Position', [150, 30, 200, 50], ...
    'Callback', @button_back_callback);

%--------------------------------------------
%BUTTON FUNCTIONS
%--------------------------------------------
    function button_back_callback(source, eventdata)
        settings_gui_advanced(f);
    end

    function saving_callback(source, eventdata)
        p.reg.characteristicWeight = str2double(editbox_characteristic_weight.String);
        p.reg.angle = str2double(editbox_reference_angle.String);
        p.reg.reference_point = [-cos(deg2rad(p.reg.angle));0; -sin(deg2rad(p.reg.angle))];
        p.reg.flipped = checkbox_flipped.Value;
        p.reg.reference_vector = (1-2*p.reg.flipped)*[-p.reg.reference_point(3);0;p.reg.reference_point(1)];
        
        p.samples_sphere = round(str2double(editbox_samples.String));
        editbox_samples.String = p.samples_sphere;
        
        p.samples_cube = [round(str2double(editbox_samples_cube_x.String));round(str2double(editbox_samples_cube_y.String));round(str2double(editbox_samples_cube_z.String))];
        editbox_samples_cube_x.String = p.samples_cube(1);
        editbox_samples_cube_y.String = p.samples_cube(2);
        editbox_samples_cube_z.String = p.samples_cube(3);
    end
end

