function settings_gui()
global changes

f = figure('Visible', 'on', 'Position', [200,400,500,500], 'MenuBar', 'None', 'NumberTitle', 'off', 'Name', 'Settings');



button_type_zebrafish = uicontrol('Style', 'togglebutton', ...
    'String', 'Zebrafish-like', ...
    'Position', [100, 430, 150, 30], ...
    'Value', isequal(changes.datatype, 'Zebrafish'), ...
    'Callback', @button_type_zebrafish_callback);
button_type_drosophila = uicontrol('Style', 'togglebutton', ...
    'String', 'Drosophila-like', ...
    'Position', [250, 430, 150, 30], ...
    'Value', isequal(changes.datatype, 'Drosophila'), ...
    'Callback', @button_type_drosophila_callback);
button_mappingtype_cells = uicontrol('Style', 'togglebutton', ...
    'String', 'Cell mapping', ...
    'Position', [100, 330, 150, 30], ...
    'Value', isequal(changes.mappingtype, 'Cells'), ...
    'Callback', @button_mappingtype_cells_callback);
button_mappingtype_tissue = uicontrol('Style', 'togglebutton', ...
    'String', 'Tissue mapping', ...
    'Position', [250, 330, 150, 30], ...
    'Value', isequal(changes.mappingtype, 'Tissue'), ...
    'Callback', @button_mappingtype_tissue_callback);


%box_type = uicontrol('Style', 'text', ...
%    'String', 'Type of data', ...
%    'Position', [50, 460, 200, 30], ...
%    'FontSize', 15);
%box_mappingtype = uicontrol('Style', 'text', ...
%    'String', 'Type of mapping', ...
%    'Position', [50,360, 200, 30], ...
%    'FontSize', 15);
box_resolution = uicontrol('Style', 'text', ...
    'String', ['Voxel size [' char(181) 'm]'], ...
    'Position', [150, 260, 200, 30], ...
    'FontSize', 15);
box_cellsize = uicontrol('Style', 'text', ...
    'String', ['Cell size [' char(181) 'm]'], ...
    'Position', [150, 160, 200, 30], ...
    'FontSize', 15);


editbox_resolution_x = uicontrol('Style', 'edit', ...
    'String', changes.resolution(1), ...
    'Position', [175,230,50,30], ...
    'Callback', @saving_callback);
editbox_resolution_y = uicontrol('Style', 'edit', ...
    'String', changes.resolution(2), ...
    'Position', [225,230,50,30], ...
    'Callback', @saving_callback);
editbox_resolution_z = uicontrol('Style', 'edit', ...
    'String', changes.resolution(3), ...
    'Position', [275,230,50,30], ...
    'Callback', @saving_callback);
editbox_cellsize = uicontrol('Style', 'edit', ...
    'String', changes.mCherryseg.cellSize, ...
    'Position', [200,130,100,30], ...
    'Callback', @saving_callback, ...
    'Enable', 'on');

if isequal(changes.mappingtype, 'Tissue')
    editbox_cellsize.Enable = 'off';
end


    function button_type_zebrafish_callback(source, eventdata)
        button_type_zebrafish.Value = 1;
        button_type_drosophila.Value = 0;
        editbox_cellsize.String = 50;
        editbox_resolution_x.String = 1.29;
        editbox_resolution_y.String = 1.29;
        editbox_resolution_z.String = 10;
        
        changes.resolution = [1.29,1.29,10];
        changes.mCherryseg.cellSize = 50;
        changes.datatype = 'Zebrafish';
    end

    function button_type_drosophila_callback(source, eventdata)
        button_type_zebrafish.Value = 0;
        button_type_drosophila.Value = 1;
        editbox_cellsize.String = 30;
        editbox_resolution_x.String = 1.29;
        editbox_resolution_y.String = 1.29;
        editbox_resolution_z.String = 5;
        
        changes.resolution = [1.29,1.29,5];
        changes.mCherryseg.cellSize = 50;
        changes.datatype = 'Drosophila';
    end

    function button_mappingtype_cells_callback(source, eventdata)
        button_mappingtype_cells.Value = 1;
        button_mappingtype_tissue.Value = 0;
        editbox_cellsize.Enable = 'on';
        
        changes.mappingtype = 'Cells';
    end

    function button_mappingtype_tissue_callback(source, eventdata)
        button_mappingtype_cells.Value = 0;
        button_mappingtype_tissue.Value = 1;
        editbox_cellsize.Enable = 'off';
        
        changes.mappingtype = 'Tissue';
    end

    function saving_callback(source, eventdata)
        changes.resolution = [str2double(editbox_resolution_x.String), str2double(editbox_resolution_y.String), str2double(editbox_resolution_z.String)];
        changes.mCherryseg.cellSize = str2double(editbox_cellsize.String);
    end
end