function [F] = geoRegObjFun_new2(data)
%% INPUT %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   data:      The 3D spherical data set.
%% OUTPUT %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   F:      The geodesic regression objective function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%

F = @(pvT) ...
    1/2*sum( abs(...
    acos( diag( ...
    data'*(...
        pvT(1:3)*cos(pvT(7:end)'*norm(pvT(4:6)))+...
    ...%pvT(4:6)/norm(pvT(4:6))*sin(pvT(7:end)'*norm(pvT(4:6))))...
        pvT(4:6)*sin(pvT(7:end)')...
            )...
    ) ).^2) );

end

 