function createfigure(X1, Y1, Z1, S1, C1, U1, V1, W1, X2, Y2, Z2, X3, Y3, Z3, X4, Y4, Z4, C2)
%CREATEFIGURE(X1, Y1, Z1, S1, C1, U1, V1, W1, X2, Y2, Z2, X3, Y3, Z3, X4, Y4, Z4, C2)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c
%  U1:  quiver3 u
%  V1:  quiver3 v
%  W1:  quiver3 w
%  X2:  vector of x data
%  Y2:  vector of y data
%  Z2:  vector of z data
%  X3:  vector of x data
%  Y3:  vector of y data
%  Z3:  vector of z data
%  X4:  scatter3 x
%  Y4:  scatter3 y
%  Z4:  scatter3 z
%  C2:  scatter3 c

%  Auto-generated by MATLAB on 08-Jun-2016 16:06:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1);

% Create quiver3
quiver3(X1,Y1,Z1,U1,V1,W1);

% Create plot3
plot3(X2,Y2,Z2,'Color',[1 0 0]);

% Create multiple lines using matrix input to plot3
plot3(X3,Y3,Z3,'Marker','o','LineStyle','none');

% Create scatter3
scatter3(X4,Y4,Z4,S1,C2,'Marker','*');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
view(axes1,[13.6999999999999 90]);
grid(axes1,'on');
